 {.deadCodeElim: on.}
when defined(windows):
  const
    libname* = "libgnunetcadet.dll"
elif defined(macosx):
  const
    libname* = "libgnunetcadet.dylib"
else:
  const
    libname* = "libgnunetcadet.so"


const
  GNUNET_MESSAGE_TYPE_TEST* = 1


const
  GNUNET_MESSAGE_TYPE_DUMMY* = 2


const
  GNUNET_MESSAGE_TYPE_DUMMY2* = 3


const
  GNUNET_MESSAGE_TYPE_RESOLVER_REQUEST* = 4


const
  GNUNET_MESSAGE_TYPE_RESOLVER_RESPONSE* = 5


const
  GNUNET_MESSAGE_TYPE_REQUEST_AGPL* = 6


const
  GNUNET_MESSAGE_TYPE_RESPONSE_AGPL* = 7


const
  GNUNET_MESSAGE_TYPE_ARM_START* = 8


const
  GNUNET_MESSAGE_TYPE_ARM_STOP* = 9


const
  GNUNET_MESSAGE_TYPE_ARM_RESULT* = 10


const
  GNUNET_MESSAGE_TYPE_ARM_STATUS* = 11


const
  GNUNET_MESSAGE_TYPE_ARM_LIST* = 12


const
  GNUNET_MESSAGE_TYPE_ARM_LIST_RESULT* = 13


const
  GNUNET_MESSAGE_TYPE_ARM_MONITOR* = 14


const
  GNUNET_MESSAGE_TYPE_ARM_TEST* = 15


const
  GNUNET_MESSAGE_TYPE_HELLO_LEGACY* = 16


const
  GNUNET_MESSAGE_TYPE_HELLO* = 17


const
  GNUNET_MESSAGE_TYPE_FRAGMENT* = 18


const
  GNUNET_MESSAGE_TYPE_FRAGMENT_ACK* = 19


const
  GNUNET_MESSAGE_TYPE_WLAN_DATA_TO_HELPER* = 39


const
  GNUNET_MESSAGE_TYPE_WLAN_DATA_FROM_HELPER* = 40


const
  GNUNET_MESSAGE_TYPE_WLAN_HELPER_CONTROL* = 41


const
  GNUNET_MESSAGE_TYPE_WLAN_ADVERTISEMENT* = 42


const
  GNUNET_MESSAGE_TYPE_WLAN_DATA* = 43


const
  GNUNET_MESSAGE_TYPE_DV_RECV* = 44


const
  GNUNET_MESSAGE_TYPE_DV_SEND* = 45


const
  GNUNET_MESSAGE_TYPE_DV_SEND_ACK* = 46


const
  GNUNET_MESSAGE_TYPE_DV_ROUTE* = 47


const
  GNUNET_MESSAGE_TYPE_DV_START* = 48


const
  GNUNET_MESSAGE_TYPE_DV_CONNECT* = 49


const
  GNUNET_MESSAGE_TYPE_DV_DISCONNECT* = 50


const
  GNUNET_MESSAGE_TYPE_DV_SEND_NACK* = 51


const
  GNUNET_MESSAGE_TYPE_DV_DISTANCE_CHANGED* = 52


const
  GNUNET_MESSAGE_TYPE_DV_BOX* = 53


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_XU_MESSAGE* = 55


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_UDP_MESSAGE* = 56


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_UDP_ACK* = 57


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_TCP_NAT_PROBE* = 60


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_TCP_WELCOME* = 61


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_ATS* = 62


const
  GNUNET_MESSAGE_TYPE_NAT_TEST* = 63


const
  GNUNET_MESSAGE_TYPE_CORE_INIT* = 64


const
  GNUNET_MESSAGE_TYPE_CORE_INIT_REPLY* = 65


const
  GNUNET_MESSAGE_TYPE_CORE_NOTIFY_CONNECT* = 67


const
  GNUNET_MESSAGE_TYPE_CORE_NOTIFY_DISCONNECT* = 68


const
  GNUNET_MESSAGE_TYPE_CORE_NOTIFY_STATUS_CHANGE* = 69


const
  GNUNET_MESSAGE_TYPE_CORE_NOTIFY_INBOUND* = 70


const
  GNUNET_MESSAGE_TYPE_CORE_NOTIFY_OUTBOUND* = 71


const
  GNUNET_MESSAGE_TYPE_CORE_SEND_REQUEST* = 74


const
  GNUNET_MESSAGE_TYPE_CORE_SEND_READY* = 75


const
  GNUNET_MESSAGE_TYPE_CORE_SEND* = 76


const
  GNUNET_MESSAGE_TYPE_CORE_MONITOR_PEERS* = 78


const
  GNUNET_MESSAGE_TYPE_CORE_MONITOR_NOTIFY* = 79


const
  GNUNET_MESSAGE_TYPE_CORE_ENCRYPTED_MESSAGE* = 82


const
  GNUNET_MESSAGE_TYPE_CORE_PING* = 83


const
  GNUNET_MESSAGE_TYPE_CORE_PONG* = 84


const
  GNUNET_MESSAGE_TYPE_CORE_HANGUP* = 85


const
  GNUNET_MESSAGE_TYPE_CORE_COMPRESSED_TYPE_MAP* = 86


const
  GNUNET_MESSAGE_TYPE_CORE_BINARY_TYPE_MAP* = 87


const
  GNUNET_MESSAGE_TYPE_CORE_EPHEMERAL_KEY* = 88


const
  GNUNET_MESSAGE_TYPE_CORE_CONFIRM_TYPE_MAP* = 89


const
  GNUNET_MESSAGE_TYPE_DATASTORE_RESERVE* = 92


const
  GNUNET_MESSAGE_TYPE_DATASTORE_RELEASE_RESERVE* = 93


const
  GNUNET_MESSAGE_TYPE_DATASTORE_STATUS* = 94


const
  GNUNET_MESSAGE_TYPE_DATASTORE_PUT* = 95


const
  GNUNET_MESSAGE_TYPE_DATASTORE_GET* = 97


const
  GNUNET_MESSAGE_TYPE_DATASTORE_GET_REPLICATION* = 98


const
  GNUNET_MESSAGE_TYPE_DATASTORE_GET_ZERO_ANONYMITY* = 99


const
  GNUNET_MESSAGE_TYPE_DATASTORE_DATA* = 100


const
  GNUNET_MESSAGE_TYPE_DATASTORE_DATA_END* = 101


const
  GNUNET_MESSAGE_TYPE_DATASTORE_REMOVE* = 102


const
  GNUNET_MESSAGE_TYPE_DATASTORE_DROP* = 103


const
  GNUNET_MESSAGE_TYPE_DATASTORE_GET_KEY* = 104


const
  GNUNET_MESSAGE_TYPE_FS_REQUEST_LOC_SIGN* = 126


const
  GNUNET_MESSAGE_TYPE_FS_REQUEST_LOC_SIGNATURE* = 127


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_START* = 128


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_START_OK* = 129


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_START_FAILED* = 130


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_LIST_GET* = 131


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_LIST_ENTRY* = 132


const
  GNUNET_MESSAGE_TYPE_FS_INDEX_LIST_END* = 133


const
  GNUNET_MESSAGE_TYPE_FS_UNINDEX* = 134


const
  GNUNET_MESSAGE_TYPE_FS_UNINDEX_OK* = 135


const
  GNUNET_MESSAGE_TYPE_FS_START_SEARCH* = 136


const
  GNUNET_MESSAGE_TYPE_FS_GET* = 137


const
  GNUNET_MESSAGE_TYPE_FS_PUT* = 138


const
  GNUNET_MESSAGE_TYPE_FS_MIGRATION_STOP* = 139


const
  GNUNET_MESSAGE_TYPE_FS_CADET_QUERY* = 140


const
  GNUNET_MESSAGE_TYPE_FS_CADET_REPLY* = 141


const
  GNUNET_MESSAGE_TYPE_DHT_CLIENT_PUT* = 142


const
  GNUNET_MESSAGE_TYPE_DHT_CLIENT_GET* = 143


const
  GNUNET_MESSAGE_TYPE_DHT_CLIENT_GET_STOP* = 144


const
  GNUNET_MESSAGE_TYPE_DHT_CLIENT_RESULT* = 145


const
  GNUNET_MESSAGE_TYPE_DHT_P2P_PUT* = 146


const
  GNUNET_MESSAGE_TYPE_DHT_P2P_GET* = 147


const
  GNUNET_MESSAGE_TYPE_DHT_P2P_RESULT* = 148


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_GET* = 149


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_GET_RESP* = 150


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_PUT* = 151


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_PUT_RESP* = 152


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_START* = 153


const
  GNUNET_MESSAGE_TYPE_DHT_MONITOR_STOP* = 154


const
  GNUNET_MESSAGE_TYPE_DHT_CLIENT_GET_RESULTS_KNOWN* = 156


const
  GNUNET_MESSAGE_TYPE_HOSTLIST_ADVERTISEMENT* = 160


const
  GNUNET_MESSAGE_TYPE_STATISTICS_SET* = 168


const
  GNUNET_MESSAGE_TYPE_STATISTICS_GET* = 169


const
  GNUNET_MESSAGE_TYPE_STATISTICS_VALUE* = 170


const
  GNUNET_MESSAGE_TYPE_STATISTICS_END* = 171


const
  GNUNET_MESSAGE_TYPE_STATISTICS_WATCH* = 172


const
  GNUNET_MESSAGE_TYPE_STATISTICS_WATCH_VALUE* = 173


const
  GNUNET_MESSAGE_TYPE_STATISTICS_DISCONNECT* = 174


const
  GNUNET_MESSAGE_TYPE_STATISTICS_DISCONNECT_CONFIRM* = 175


const
  GNUNET_MESSAGE_TYPE_VPN_HELPER* = 185


const
  GNUNET_MESSAGE_TYPE_VPN_ICMP_TO_SERVICE* = 190


const
  GNUNET_MESSAGE_TYPE_VPN_ICMP_TO_INTERNET* = 191


const
  GNUNET_MESSAGE_TYPE_VPN_ICMP_TO_VPN* = 192


const
  GNUNET_MESSAGE_TYPE_VPN_DNS_TO_INTERNET* = 193


const
  GNUNET_MESSAGE_TYPE_VPN_DNS_FROM_INTERNET* = 194


const
  GNUNET_MESSAGE_TYPE_VPN_TCP_TO_SERVICE_START* = 195


const
  GNUNET_MESSAGE_TYPE_VPN_TCP_TO_INTERNET_START* = 196


const
  GNUNET_MESSAGE_TYPE_VPN_TCP_DATA_TO_EXIT* = 197


const
  GNUNET_MESSAGE_TYPE_VPN_TCP_DATA_TO_VPN* = 198


const
  GNUNET_MESSAGE_TYPE_VPN_UDP_TO_SERVICE* = 199


const
  GNUNET_MESSAGE_TYPE_VPN_UDP_TO_INTERNET* = 200


const
  GNUNET_MESSAGE_TYPE_VPN_UDP_REPLY* = 201


const
  GNUNET_MESSAGE_TYPE_VPN_CLIENT_REDIRECT_TO_IP* = 202


const
  GNUNET_MESSAGE_TYPE_VPN_CLIENT_REDIRECT_TO_SERVICE* = 203


const
  GNUNET_MESSAGE_TYPE_VPN_CLIENT_USE_IP* = 204


const
  GNUNET_MESSAGE_TYPE_DNS_CLIENT_INIT* = 211


const
  GNUNET_MESSAGE_TYPE_DNS_CLIENT_REQUEST* = 212


const
  GNUNET_MESSAGE_TYPE_DNS_CLIENT_RESPONSE* = 213


const
  GNUNET_MESSAGE_TYPE_DNS_HELPER* = 214


const
  GNUNET_MESSAGE_TYPE_CHAT_JOIN_REQUEST* = 300


const
  GNUNET_MESSAGE_TYPE_CHAT_JOIN_NOTIFICATION* = 301


const
  GNUNET_MESSAGE_TYPE_CHAT_LEAVE_NOTIFICATION* = 302


const
  GNUNET_MESSAGE_TYPE_CHAT_MESSAGE_NOTIFICATION* = 303


const
  GNUNET_MESSAGE_TYPE_CHAT_TRANSMIT_REQUEST* = 304


const
  GNUNET_MESSAGE_TYPE_CHAT_CONFIRMATION_RECEIPT* = 305


const
  GNUNET_MESSAGE_TYPE_CHAT_CONFIRMATION_NOTIFICATION* = 306


const
  GNUNET_MESSAGE_TYPE_CHAT_P2P_JOIN_NOTIFICATION* = 307


const
  GNUNET_MESSAGE_TYPE_CHAT_P2P_LEAVE_NOTIFICATION* = 308


const
  GNUNET_MESSAGE_TYPE_CHAT_P2P_SYNC_REQUEST* = 309


const
  GNUNET_MESSAGE_TYPE_CHAT_P2P_MESSAGE_NOTIFICATION* = 310


const
  GNUNET_MESSAGE_TYPE_CHAT_P2P_CONFIRMATION_RECEIPT* = 311


const
  GNUNET_MESSAGE_TYPE_NSE_START* = 321


const
  GNUNET_MESSAGE_TYPE_NSE_P2P_FLOOD* = 322


const
  GNUNET_MESSAGE_TYPE_NSE_ESTIMATE* = 323


const
  GNUNET_MESSAGE_TYPE_PEERINFO_GET* = 330


const
  GNUNET_MESSAGE_TYPE_PEERINFO_GET_ALL* = 331


const
  GNUNET_MESSAGE_TYPE_PEERINFO_INFO* = 332


const
  GNUNET_MESSAGE_TYPE_PEERINFO_INFO_END* = 333


const
  GNUNET_MESSAGE_TYPE_PEERINFO_NOTIFY* = 334


const
  GNUNET_MESSAGE_TYPE_ATS_START* = 340


const
  GNUNET_MESSAGE_TYPE_ATS_REQUEST_ADDRESS* = 341


const
  GNUNET_MESSAGE_TYPE_ATS_REQUEST_ADDRESS_CANCEL* = 342


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESS_UPDATE* = 343


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESS_DESTROYED* = 344


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESS_SUGGESTION* = 345


const
  GNUNET_MESSAGE_TYPE_ATS_PEER_INFORMATION* = 346


const
  GNUNET_MESSAGE_TYPE_ATS_RESERVATION_REQUEST* = 347


const
  GNUNET_MESSAGE_TYPE_ATS_RESERVATION_RESULT* = 348


const
  GNUNET_MESSAGE_TYPE_ATS_PREFERENCE_CHANGE* = 349


const
  GNUNET_MESSAGE_TYPE_ATS_SESSION_RELEASE* = 350


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESS_ADD* = 353


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESSLIST_REQUEST* = 354


const
  GNUNET_MESSAGE_TYPE_ATS_ADDRESSLIST_RESPONSE* = 355


const
  GNUNET_MESSAGE_TYPE_ATS_PREFERENCE_FEEDBACK* = 356


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_START* = 360


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_CONNECT* = 361


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_DISCONNECT* = 362


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SEND* = 363


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SEND_OK* = 364


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_RECV* = 365


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SET_QUOTA* = 366


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_ADDRESS_TO_STRING* = 367


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_ADDRESS_TO_STRING_REPLY* = 368


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_BLACKLIST_INIT* = 369


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_BLACKLIST_QUERY* = 370


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_BLACKLIST_REPLY* = 371


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_PING* = 372


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_PONG* = 373


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_SYN* = 375


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_SYN_ACK* = 376


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_ACK* = 377


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_DISCONNECT* = 378


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_QUOTA* = 379


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PEER_REQUEST* = 380


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_KEEPALIVE* = 381


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_SESSION_KEEPALIVE_RESPONSE* = 382


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PEER_RESPONSE* = 383


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_BROADCAST_BEACON* = 384


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_TRAFFIC_METRIC* = 385


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PLUGIN_START* = 388


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PLUGIN_EVENT* = 389


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PLUGIN_SYNC* = 390


const
  GNUNET_MESSAGE_TYPE_TRANSPORT_MONITOR_PEER_RESPONSE_END* = 391


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_PROGRESS_FILE* = 420


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_PROGRESS_DIRECTORY* = 421


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_ERROR* = 422


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_SKIP_FILE* = 423


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_COUNTING_DONE* = 424


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_META_DATA* = 425


const
  GNUNET_MESSAGE_TYPE_FS_PUBLISH_HELPER_FINISHED* = 426


const
  GNUNET_MESSAGE_TYPE_NAMECACHE_LOOKUP_BLOCK* = 431


const
  GNUNET_MESSAGE_TYPE_NAMECACHE_LOOKUP_BLOCK_RESPONSE* = 432


const
  GNUNET_MESSAGE_TYPE_NAMECACHE_BLOCK_CACHE* = 433


const
  GNUNET_MESSAGE_TYPE_NAMECACHE_BLOCK_CACHE_RESPONSE* = 434


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_RECORD_STORE* = 435


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_RECORD_STORE_RESPONSE* = 436


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_RECORD_LOOKUP* = 437


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_RECORD_LOOKUP_RESPONSE* = 438


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_ZONE_TO_NAME* = 439


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_ZONE_TO_NAME_RESPONSE* = 440


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_MONITOR_START* = 441


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_MONITOR_SYNC* = 442


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_RECORD_RESULT* = 443


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_MONITOR_NEXT* = 444


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_ZONE_ITERATION_START* = 445


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_ZONE_ITERATION_NEXT* = 447


const
  GNUNET_MESSAGE_TYPE_NAMESTORE_ZONE_ITERATION_STOP* = 448


const
  GNUNET_MESSAGE_TYPE_LOCKMANAGER_ACQUIRE* = 450


const
  GNUNET_MESSAGE_TYPE_LOCKMANAGER_RELEASE* = 451


const
  GNUNET_MESSAGE_TYPE_LOCKMANAGER_SUCCESS* = 452


const
  GNUNET_MESSAGE_TYPE_TESTBED_INIT* = 460


const
  GNUNET_MESSAGE_TYPE_TESTBED_ADD_HOST* = 461


const
  GNUNET_MESSAGE_TYPE_TESTBED_ADD_HOST_SUCCESS* = 462


const
  GNUNET_MESSAGE_TYPE_TESTBED_LINK_CONTROLLERS* = 463


const
  GNUNET_MESSAGE_TYPE_TESTBED_CREATE_PEER* = 464


const
  GNUNET_MESSAGE_TYPE_TESTBED_RECONFIGURE_PEER* = 465


const
  GNUNET_MESSAGE_TYPE_TESTBED_START_PEER* = 466


const
  GNUNET_MESSAGE_TYPE_TESTBED_STOP_PEER* = 467


const
  GNUNET_MESSAGE_TYPE_TESTBED_DESTROY_PEER* = 468


const
  GNUNET_MESSAGE_TYPE_TESTBED_CONFIGURE_UNDERLAY_LINK* = 469


const
  GNUNET_MESSAGE_TYPE_TESTBED_OVERLAY_CONNECT* = 470


const
  GNUNET_MESSAGE_TYPE_TESTBED_PEER_EVENT* = 471


const
  GNUNET_MESSAGE_TYPE_TESTBED_PEER_CONNECT_EVENT* = 472


const
  GNUNET_MESSAGE_TYPE_TESTBED_OPERATION_FAIL_EVENT* = 473


const
  GNUNET_MESSAGE_TYPE_TESTBED_CREATE_PEER_SUCCESS* = 474


const
  GNUNET_MESSAGE_TYPE_TESTBED_GENERIC_OPERATION_SUCCESS* = 475


const
  GNUNET_MESSAGE_TYPE_TESTBED_GET_PEER_INFORMATION* = 476


const
  GNUNET_MESSAGE_TYPE_TESTBED_PEER_INFORMATION* = 477


const
  GNUNET_MESSAGE_TYPE_TESTBED_REMOTE_OVERLAY_CONNECT* = 478


const
  GNUNET_MESSAGE_TYPE_TESTBED_GET_SLAVE_CONFIGURATION* = 479


const
  GNUNET_MESSAGE_TYPE_TESTBED_SLAVE_CONFIGURATION* = 480


const
  GNUNET_MESSAGE_TYPE_TESTBED_LINK_CONTROLLERS_RESULT* = 481


const
  GNUNET_MESSAGE_TYPE_TESTBED_SHUTDOWN_PEERS* = 482


const
  GNUNET_MESSAGE_TYPE_TESTBED_MANAGE_PEER_SERVICE* = 483


const
  GNUNET_MESSAGE_TYPE_TESTBED_BARRIER_INIT* = 484


const
  GNUNET_MESSAGE_TYPE_TESTBED_BARRIER_CANCEL* = 485


const
  GNUNET_MESSAGE_TYPE_TESTBED_BARRIER_STATUS* = 486


const
  GNUNET_MESSAGE_TYPE_TESTBED_BARRIER_WAIT* = 487


const
  GNUNET_MESSAGE_TYPE_TESTBED_MAX* = 488


const
  GNUNET_MESSAGE_TYPE_TESTBED_HELPER_INIT* = 495


const
  GNUNET_MESSAGE_TYPE_TESTBED_HELPER_REPLY* = 496


const
  GNUNET_MESSAGE_TYPE_GNS_LOOKUP* = 500


const
  GNUNET_MESSAGE_TYPE_GNS_LOOKUP_RESULT* = 501


const
  GNUNET_MESSAGE_TYPE_GNS_REVERSE_LOOKUP* = 503


const
  GNUNET_MESSAGE_TYPE_GNS_REVERSE_LOOKUP_RESULT* = 504


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_JOIN* = 520


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_INSERT* = 521


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_BEGIN* = 522


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_RECEIVED_ELEMENT* = 523


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_CONCLUDE* = 524


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_CONCLUDE_DONE* = 525


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_CLIENT_ACK* = 540


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_DELTA_ESTIMATE* = 541


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_DIFFERENCE_DIGEST* = 542


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_ELEMENTS* = 543


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_ELEMENTS_REQUEST* = 544


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_ELEMENTS_REPORT* = 545


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_HELLO* = 546


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_SYNCED* = 547


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_FIN* = 548


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_ABORT* = 548


const
  GNUNET_MESSAGE_TYPE_CONSENSUS_P2P_ROUND_CONTEXT* = 547


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_REQUEST_FULL* = 565


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_DEMAND* = 566


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_INQUIRY* = 567


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_OFFER* = 568


const
  GNUNET_MESSAGE_TYPE_SET_REJECT* = 569


const
  GNUNET_MESSAGE_TYPE_SET_CANCEL* = 570


const
  GNUNET_MESSAGE_TYPE_SET_ITER_ACK* = 571


const
  GNUNET_MESSAGE_TYPE_SET_RESULT* = 572


const
  GNUNET_MESSAGE_TYPE_SET_ADD* = 573


const
  GNUNET_MESSAGE_TYPE_SET_REMOVE* = 574


const
  GNUNET_MESSAGE_TYPE_SET_LISTEN* = 575


const
  GNUNET_MESSAGE_TYPE_SET_ACCEPT* = 576


const
  GNUNET_MESSAGE_TYPE_SET_EVALUATE* = 577


const
  GNUNET_MESSAGE_TYPE_SET_CONCLUDE* = 578


const
  GNUNET_MESSAGE_TYPE_SET_REQUEST* = 579


const
  GNUNET_MESSAGE_TYPE_SET_CREATE* = 580


const
  GNUNET_MESSAGE_TYPE_SET_P2P_OPERATION_REQUEST* = 581


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_SE* = 582


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_IBF* = 583


const
  GNUNET_MESSAGE_TYPE_SET_P2P_ELEMENTS* = 584


const
  GNUNET_MESSAGE_TYPE_SET_P2P_ELEMENT_REQUESTS* = 585


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_DONE* = 586


const
  GNUNET_MESSAGE_TYPE_SET_ITER_REQUEST* = 587


const
  GNUNET_MESSAGE_TYPE_SET_ITER_ELEMENT* = 588


const
  GNUNET_MESSAGE_TYPE_SET_ITER_DONE* = 589


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_SEC* = 590


const
  GNUNET_MESSAGE_TYPE_SET_INTERSECTION_P2P_ELEMENT_INFO* = 591


const
  GNUNET_MESSAGE_TYPE_SET_INTERSECTION_P2P_BF* = 592


const
  GNUNET_MESSAGE_TYPE_SET_INTERSECTION_P2P_DONE* = 593


const
  GNUNET_MESSAGE_TYPE_SET_COPY_LAZY_PREPARE* = 594


const
  GNUNET_MESSAGE_TYPE_SET_COPY_LAZY_RESPONSE* = 595


const
  GNUNET_MESSAGE_TYPE_SET_COPY_LAZY_CONNECT* = 596


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_FULL_DONE* = 597


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_FULL_ELEMENT* = 598


const
  GNUNET_MESSAGE_TYPE_SET_UNION_P2P_OVER* = 599


const
  GNUNET_MESSAGE_TYPE_TESTBED_LOGGER_MSG* = 600


const
  GNUNET_MESSAGE_TYPE_TESTBED_LOGGER_ACK* = 601


const
  GNUNET_MESSAGE_TYPE_REGEX_ANNOUNCE* = 620


const
  GNUNET_MESSAGE_TYPE_REGEX_SEARCH* = 621


const
  GNUNET_MESSAGE_TYPE_REGEX_RESULT* = 622


const
  GNUNET_MESSAGE_TYPE_IDENTITY_START* = 624


const
  GNUNET_MESSAGE_TYPE_IDENTITY_RESULT_CODE* = 625


const
  GNUNET_MESSAGE_TYPE_IDENTITY_UPDATE* = 626


const
  GNUNET_MESSAGE_TYPE_IDENTITY_GET_DEFAULT* = 627


const
  GNUNET_MESSAGE_TYPE_IDENTITY_SET_DEFAULT* = 628


const
  GNUNET_MESSAGE_TYPE_IDENTITY_CREATE* = 629


const
  GNUNET_MESSAGE_TYPE_IDENTITY_RENAME* = 630


const
  GNUNET_MESSAGE_TYPE_IDENTITY_DELETE* = 631


const
  GNUNET_MESSAGE_TYPE_REVOCATION_QUERY* = 636


const
  GNUNET_MESSAGE_TYPE_REVOCATION_QUERY_RESPONSE* = 637


const
  GNUNET_MESSAGE_TYPE_REVOCATION_REVOKE* = 638


const
  GNUNET_MESSAGE_TYPE_REVOCATION_REVOKE_RESPONSE* = 639


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_CLIENT_TO_ALICE* = 640


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_CLIENT_TO_BOB* = 641


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_CLIENT_MULTIPART_ALICE* = 642


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_CLIENT_MULTIPART_BOB* = 643


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_SESSION_INITIALIZATION* = 644


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_ALICE_CRYPTODATA* = 645


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_BOB_CRYPTODATA* = 647


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_BOB_CRYPTODATA_MULTIPART* = 648


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_RESULT* = 649


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_ECC_SESSION_INITIALIZATION* = 650


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_ECC_ALICE_CRYPTODATA* = 651


const
  GNUNET_MESSAGE_TYPE_SCALARPRODUCT_ECC_BOB_CRYPTODATA* = 652


const
  GNUNET_MESSAGE_TYPE_PSYCSTORE_MEMBERSHIP_STORE* = 660


const
  GNUNET_MESSAGE_TYPE_PSYCSTORE_MEMBERSHIP_TEST* = 661
  GNUNET_MESSAGE_TYPE_PSYCSTORE_FRAGMENT_STORE* = 662
  GNUNET_MESSAGE_TYPE_PSYCSTORE_FRAGMENT_GET* = 663
  GNUNET_MESSAGE_TYPE_PSYCSTORE_MESSAGE_GET* = 664
  GNUNET_MESSAGE_TYPE_PSYCSTORE_MESSAGE_GET_FRAGMENT* = 665
  GNUNET_MESSAGE_TYPE_PSYCSTORE_COUNTERS_GET* = 666


const
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_MODIFY* = 668
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_SYNC* = 669
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_RESET* = 670
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_HASH_UPDATE* = 671
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_GET* = 672
  GNUNET_MESSAGE_TYPE_PSYCSTORE_STATE_GET_PREFIX* = 673


const
  GNUNET_MESSAGE_TYPE_PSYCSTORE_RESULT_CODE* = 674
  GNUNET_MESSAGE_TYPE_PSYCSTORE_RESULT_FRAGMENT* = 675
  GNUNET_MESSAGE_TYPE_PSYCSTORE_RESULT_COUNTERS* = 676
  GNUNET_MESSAGE_TYPE_PSYCSTORE_RESULT_STATE* = 677


const
  GNUNET_MESSAGE_TYPE_PSYC_RESULT_CODE* = 680


const
  GNUNET_MESSAGE_TYPE_PSYC_MASTER_START* = 681


const
  GNUNET_MESSAGE_TYPE_PSYC_MASTER_START_ACK* = 682


const
  GNUNET_MESSAGE_TYPE_PSYC_SLAVE_JOIN* = 683


const
  GNUNET_MESSAGE_TYPE_PSYC_SLAVE_JOIN_ACK* = 684


const
  GNUNET_MESSAGE_TYPE_PSYC_PART_REQUEST* = 685


const
  GNUNET_MESSAGE_TYPE_PSYC_PART_ACK* = 686


const
  GNUNET_MESSAGE_TYPE_PSYC_JOIN_REQUEST* = 687


const
  GNUNET_MESSAGE_TYPE_PSYC_JOIN_DECISION* = 688


const
  GNUNET_MESSAGE_TYPE_PSYC_CHANNEL_MEMBERSHIP_STORE* = 689


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE* = 691


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_HEADER* = 692


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_METHOD* = 693


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_MODIFIER* = 694


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_MOD_CONT* = 695


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_DATA* = 696


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_END* = 697


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_CANCEL* = 698


const
  GNUNET_MESSAGE_TYPE_PSYC_MESSAGE_ACK* = 699


const
  GNUNET_MESSAGE_TYPE_PSYC_HISTORY_REPLAY* = 701


const
  GNUNET_MESSAGE_TYPE_PSYC_HISTORY_RESULT* = 702


const
  GNUNET_MESSAGE_TYPE_PSYC_STATE_GET* = 703


const
  GNUNET_MESSAGE_TYPE_PSYC_STATE_GET_PREFIX* = 704


const
  GNUNET_MESSAGE_TYPE_PSYC_STATE_RESULT* = 705


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_AUDIO* = 730


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_REGISTER* = 731


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_PICK_UP* = 732


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_HANG_UP* = 733


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_CALL* = 734


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_RING* = 735


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_SUSPEND* = 736


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_RESUME* = 737


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_PHONE_PICKED_UP* = 738


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CS_AUDIO* = 739


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_PHONE_RING* = 740


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_PHONE_HANG_UP* = 741


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_PHONE_PICK_UP* = 742


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_PHONE_SUSPEND* = 743


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_PHONE_RESUME* = 744


const
  GNUNET_MESSAGE_TYPE_CONVERSATION_CADET_AUDIO* = 745


const
  GNUNET_MESSAGE_TYPE_MULTICAST_ORIGIN_START* = 750


const
  GNUNET_MESSAGE_TYPE_MULTICAST_MEMBER_JOIN* = 751


const
  GNUNET_MESSAGE_TYPE_MULTICAST_JOIN_REQUEST* = 752


const
  GNUNET_MESSAGE_TYPE_MULTICAST_JOIN_DECISION* = 753


const
  GNUNET_MESSAGE_TYPE_MULTICAST_PART_REQUEST* = 754


const
  GNUNET_MESSAGE_TYPE_MULTICAST_PART_ACK* = 755


const
  GNUNET_MESSAGE_TYPE_MULTICAST_GROUP_END* = 756


const
  GNUNET_MESSAGE_TYPE_MULTICAST_MESSAGE* = 757


const
  GNUNET_MESSAGE_TYPE_MULTICAST_REQUEST* = 758


const
  GNUNET_MESSAGE_TYPE_MULTICAST_FRAGMENT_ACK* = 759


const
  GNUNET_MESSAGE_TYPE_MULTICAST_REPLAY_REQUEST* = 760


const
  GNUNET_MESSAGE_TYPE_MULTICAST_REPLAY_RESPONSE* = 761


const
  GNUNET_MESSAGE_TYPE_MULTICAST_REPLAY_RESPONSE_END* = 762


const
  GNUNET_MESSAGE_TYPE_SECRETSHARING_CLIENT_GENERATE* = 780


const
  GNUNET_MESSAGE_TYPE_SECRETSHARING_CLIENT_DECRYPT* = 781


const
  GNUNET_MESSAGE_TYPE_SECRETSHARING_CLIENT_DECRYPT_DONE* = 782


const
  GNUNET_MESSAGE_TYPE_SECRETSHARING_CLIENT_SECRET_READY* = 783


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_STORE* = 820


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_ITERATE* = 821


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_ITERATE_RECORD* = 822


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_ITERATE_END* = 823


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_WATCH* = 824


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_WATCH_RECORD* = 825


const
  GNUNET_MESSAGE_TYPE_PEERSTORE_WATCH_CANCEL* = 826


const
  GNUNET_MESSAGE_TYPE_SOCIAL_RESULT_CODE* = 840


const
  GNUNET_MESSAGE_TYPE_SOCIAL_HOST_ENTER* = 841


const
  GNUNET_MESSAGE_TYPE_SOCIAL_HOST_ENTER_ACK* = 842


const
  GNUNET_MESSAGE_TYPE_SOCIAL_GUEST_ENTER* = 843


const
  GNUNET_MESSAGE_TYPE_SOCIAL_GUEST_ENTER_BY_NAME* = 844


const
  GNUNET_MESSAGE_TYPE_SOCIAL_GUEST_ENTER_ACK* = 845


const
  GNUNET_MESSAGE_TYPE_SOCIAL_ENTRY_REQUEST* = 846


const
  GNUNET_MESSAGE_TYPE_SOCIAL_ENTRY_DECISION* = 847


const
  GNUNET_MESSAGE_TYPE_SOCIAL_PLACE_LEAVE* = 848


const
  GNUNET_MESSAGE_TYPE_SOCIAL_PLACE_LEAVE_ACK* = 849


const
  GNUNET_MESSAGE_TYPE_SOCIAL_ZONE_ADD_PLACE* = 850


const
  GNUNET_MESSAGE_TYPE_SOCIAL_ZONE_ADD_NYM* = 851


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_CONNECT* = 852


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_DETACH* = 853


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_EGO* = 854


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_EGO_END* = 855


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_PLACE* = 856


const
  GNUNET_MESSAGE_TYPE_SOCIAL_APP_PLACE_END* = 857


const
  GNUNET_MESSAGE_TYPE_SOCIAL_MSG_PROC_SET* = 858


const
  GNUNET_MESSAGE_TYPE_SOCIAL_MSG_PROC_CLEAR* = 859


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_TRAIL_SETUP* = 880


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_TRAIL_SETUP_RESULT* = 881


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_VERIFY_SUCCESSOR* = 882


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_NOTIFY_NEW_SUCCESSOR* = 883


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_VERIFY_SUCCESSOR_RESULT* = 884


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_GET_RESULT* = 885


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_TRAIL_SETUP_REJECTION* = 886


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_TRAIL_TEARDOWN* = 887


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_ADD_TRAIL* = 888


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_PUT* = 890


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_GET* = 891


const
  GNUNET_MESSAGE_TYPE_XDHT_P2P_NOTIFY_SUCCESSOR_CONFIRMATION* = 892


const
  GNUNET_MESSAGE_TYPE_WDHT_RANDOM_WALK* = 910


const
  GNUNET_MESSAGE_TYPE_WDHT_RANDOM_WALK_RESPONSE* = 911


const
  GNUNET_MESSAGE_TYPE_WDHT_TRAIL_DESTROY* = 912


const
  GNUNET_MESSAGE_TYPE_WDHT_TRAIL_ROUTE* = 913


const
  GNUNET_MESSAGE_TYPE_WDHT_SUCCESSOR_FIND* = 914


const
  GNUNET_MESSAGE_TYPE_WDHT_GET* = 915


const
  GNUNET_MESSAGE_TYPE_WDHT_PUT* = 916


const
  GNUNET_MESSAGE_TYPE_WDHT_GET_RESULT* = 917


const
  GNUNET_MESSAGE_TYPE_RPS_PP_CHECK_LIVE* = 950


const
  GNUNET_MESSAGE_TYPE_RPS_PP_PUSH* = 951


const
  GNUNET_MESSAGE_TYPE_RPS_PP_PULL_REQUEST* = 952


const
  GNUNET_MESSAGE_TYPE_RPS_PP_PULL_REPLY* = 953


const
  GNUNET_MESSAGE_TYPE_RPS_CS_REQUEST* = 954


const
  GNUNET_MESSAGE_TYPE_RPS_CS_REPLY* = 955


const
  GNUNET_MESSAGE_TYPE_RPS_CS_REQUEST_CANCEL* = 956


const
  GNUNET_MESSAGE_TYPE_RPS_CS_SEED* = 957


const
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_STORE* = 961
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_STORE_RESPONSE* = 962
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_ITERATION_START* = 963
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_ITERATION_STOP* = 964
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_ITERATION_NEXT* = 965
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ATTRIBUTE_RESULT* = 966
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_ISSUE_TICKET* = 967
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_TICKET_RESULT* = 968
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_REVOKE_TICKET* = 969
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_REVOKE_TICKET_RESULT* = 970
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_CONSUME_TICKET* = 971
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_CONSUME_TICKET_RESULT* = 972
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_TICKET_ITERATION_START* = 973
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_TICKET_ITERATION_STOP* = 974
  GNUNET_MESSAGE_TYPE_IDENTITY_PROVIDER_TICKET_ITERATION_NEXT* = 975


const
  GNUNET_MESSAGE_TYPE_CREDENTIAL_VERIFY* = 981
  GNUNET_MESSAGE_TYPE_CREDENTIAL_VERIFY_RESULT* = 982
  GNUNET_MESSAGE_TYPE_CREDENTIAL_COLLECT* = 983
  GNUNET_MESSAGE_TYPE_CREDENTIAL_COLLECT_RESULT* = 984


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_CREATE* = 1000


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_CREATE_ACK* = 1001


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_BROKEN* = 1002


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_DESTROY* = 1003


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_PATH_CHANGED_UNIMPLEMENTED* = 1004


const
  GNUNET_MESSAGE_TYPE_CADET_CONNECTION_HOP_BY_HOP_ENCRYPTED_ACK* = 1005


const
  GNUNET_MESSAGE_TYPE_CADET_TUNNEL_ENCRYPTED_POLL* = 1006


const
  GNUNET_MESSAGE_TYPE_CADET_TUNNEL_KX* = 1007


const
  GNUNET_MESSAGE_TYPE_CADET_TUNNEL_ENCRYPTED* = 1008


const
  GNUNET_MESSAGE_TYPE_CADET_TUNNEL_KX_AUTH* = 1009


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_APP_DATA* = 1010


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_APP_DATA_ACK* = 1011


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_KEEPALIVE* = 1012


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_OPEN* = 1013


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_DESTROY* = 1014


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_OPEN_ACK* = 1015


const
  GNUNET_MESSAGE_TYPE_CADET_CHANNEL_OPEN_NACK_DEPRECATED* = 1016


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_DATA* = 1020


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_ACK* = 1021


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_PORT_OPEN* = 1022


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_PORT_CLOSE* = 1023


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_CHANNEL_CREATE* = 1024


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_CHANNEL_DESTROY* = 1025


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_CHANNELS* = 1030


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_CHANNEL* = 1031


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_TUNNELS* = 1032


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_TUNNEL* = 1033


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_CONNECTIONS* = 1034


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_CONNECTION* = 1035


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_PEERS* = 1036


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_PEER* = 1037


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_DUMP* = 1038


const
  GNUNET_MESSAGE_TYPE_CADET_LOCAL_INFO_PEER_END* = 1039


const
  GNUNET_MESSAGE_TYPE_CADET_CLI* = 1040


const
  GNUNET_MESSAGE_TYPE_NAT_REGISTER* = 1060


const
  GNUNET_MESSAGE_TYPE_NAT_HANDLE_STUN* = 1061


const
  GNUNET_MESSAGE_TYPE_NAT_REQUEST_CONNECTION_REVERSAL* = 1062


const
  GNUNET_MESSAGE_TYPE_NAT_CONNECTION_REVERSAL_REQUESTED* = 1063


const
  GNUNET_MESSAGE_TYPE_NAT_ADDRESS_CHANGE* = 1064


const
  GNUNET_MESSAGE_TYPE_NAT_AUTO_REQUEST_CFG* = 1067


const
  GNUNET_MESSAGE_TYPE_NAT_AUTO_CFG_RESULT* = 1068


const
  GNUNET_MESSAGE_TYPE_AUCTION_CLIENT_CREATE* = 1110


const
  GNUNET_MESSAGE_TYPE_AUCTION_CLIENT_JOIN* = 1111


const
  GNUNET_MESSAGE_TYPE_AUCTION_CLIENT_OUTCOME* = 1112


const
  GNUNET_MESSAGE_TYPE_RPS_CS_DEBUG_VIEW_REQUEST* = 1130


const
  GNUNET_MESSAGE_TYPE_RPS_CS_DEBUG_VIEW_REPLY* = 1131


const
  GNUNET_MESSAGE_TYPE_RPS_CS_DEBUG_VIEW_CANCEL* = 1132


const
  GNUNET_MESSAGE_TYPE_ALL* = 65535


